cargomarket/cargomarket/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy, include
from django.contrib.auth.views import LoginView, LogoutView
from account.views import register, myprofile, home, change_password ,myprofile_edit, user_list,show_profile
from advertisement.views import ad_list, my_ad, update_ad, create_ad, detail_ad, delete_ad, all_ad ,recourse ,my_recourse, applicants_list ,state_set

urlpatterns = [
    path('', ad_list, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('accounts/register/', register, name='register'),
    path('accounts/myprofile/', myprofile, name='myprofile'),
    path('accounts/myprofile_edit/', myprofile_edit, name='myprofile_edit'),
    path('accounts/profile/id=<int:user_id>', show_profile, name='show_profile'),
    path('accounts/password/', change_password, name='password'),
    path('accounts/users/', user_list, name='users'),
    path('my_advertisement/', my_ad, name='my_ad'), 
    path('edit_advertiesement/<int:ad_id>', update_ad, name='edit_ad'),
    path('create_advertiesement/', create_ad, name='create_ad'),
    path('detail_advertiesement/<int:ad_id>', detail_ad, name='detail_ad'),
    path('delete_advertiesement/<int:ad_id>', delete_ad, name='delete_ad'),
    path('all_advertiesement/', all_ad, name='all_ad'), 
    path('recourse_advertiesement/<int:ad_id>', recourse, name='recourse'),
    path('my_recourse/', my_recourse, name='my_recourse'), 
    path('applicants/<int:ad_id>', applicants_list, name='app_list'),
    path('applicants/<int:app_id>/<int:state>', state_set, name='state_set'),
    path('chat/', include('chatapp.urls')),
]

cargomarket/chatapp/urls.py
from django.urls import path
from . import views

app_name = "chatapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('room/<str:room_name>/', views.room, name='room'),
    path('load/messages/', views.get_message, name='chat_message'),
    path('create/chat/', views.create_chat, name='create_chat'),
]

cargomarket/chatapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Chat(models.Model):
    members = models.ManyToManyField(User, related_name="chats")
    update_time = models.DateTimeField(auto_now=True)


class Message(models.Model):
    class Meta:
        ordering = ['send_time']

    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    message_text = models.CharField("message", max_length=100)
    send_time = models.DateTimeField(auto_now_add=True)


# Client1 -> WS1 -> Server -> CH1 

# CH1 -> Server -> WS2 -> Client2
#        Server -> WS3 -> Client3
#        Server -> WS1 -> Client1

cargomarket/chatapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.core.serializers import serialize
from chatapp.models import *

# Create your views here.


def get_minute(minute):
    if minute < 10:
        return "0{}".format(minute)
    return minute


@login_required
def index(request):
    chats = request.user.chats.all().order_by('-update_time')[:30]
    return render(request, 'chatapp/index.html', context={"chats": chats, "current_user": request.user})

@login_required
def get_message(request):
    chat_id = request.POST.get('chat_id', None)
    if chat_id is None:
        return JsonResponse({"status": "Error, chat_id is required"}, status=401)
    
    chat = list(Chat.objects.filter(id=chat_id, members__in=[request.user]))[0]
    messages = list(Message.objects.filter(chat=chat))[:100]

    payload = []
    for m in messages:
        payload.append({
            "message_text": m.message_text,
            "sender": m.sender.id,
            "send_time": "{}:{}".format(m.send_time.hour, get_minute(m.send_time.minute))
        })

    return JsonResponse({"messages": payload}, status=200)

@login_required
def create_chat(request):
    target_user_id = request.POST.get('target_user_id', None)
    target_user = User.objects.get(id=target_user_id)

    chat = Chat.objects.filter(members__in=[request.user]).filter(members__in=[target_user])
    if chat.count() == 0:
        c = Chat()
        c.save()
        c.members.add(target_user)
        c.members.add(request.user)
        c.save()
        return JsonResponse({"chat_id": c.id}, status=201)
    return JsonResponse({"chat_id": chat[0].id}, status=200)
    

def room(request, room_name):
    return render(request, 'chatapp/room.html', {
        'room_name': room_name
    })

cargomarket/chatapp/templates/chatapp/index.html
{% extends "base/base.html" %}

{% block title %} Chats {% endblock %}

{% block jscript %}
<script>
    var current_user_id = {{ current_user.id }};
    var active_chat_id;
    var active_chat_user_id;
    var active_chat_user_name;

    var chatSocket;
    var roomName;

    // RECEIVE MESSAGES FROM SERVER 
    function load_message(chat_id){
        console.log(chat_id);
        $.ajax({
            url: '{% url "chatapp:chat_message" %}',
            method: "POST",
            data: {
                "chat_id": chat_id,
                "csrfmiddlewaretoken": '{{ csrf_token }}',
            },
            dataType: 'json',
            success: function(data){
                write_messages_to_panel(data);
            },
            error: function(err){
                console.log(err);
            }
        })
    }

    $(document).ready(function(){
        const urlParams = new URLSearchParams(window.location.search);
        chat_id = urlParams.get("chat_id");
        if (chat_id == null) {
            console.log("Chat ID did not provided");
        }
        else {
            console.log("Chat id: " + chat_id);
            select_chat(chat_id);
        }
    });


    // SEND MESSAGES TO SERVER
    // const roomName = JSON.parse(document.getElementById('room-name').textContent);

    function open_websocket() {
        if (current_user_id < active_chat_user_id){
            roomName = "chatx" + current_user_id + "x" + active_chat_user_id;
        } else {
            roomName = "chatx" + active_chat_user_id + "x" + current_user_id;
        }
        chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        // SOCKET MESSAGE
        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            console.log(data);
            if (data.sender == current_user_id){
                $(".chat-box").append(me_message(data.message, data.send_time));
            }
            else {
                $(".chat-box").append(friend_message(data.message, data.send_time));
            }
            $(".chat-container").get(0).scrollTop += 9999;

        };

        // SOCKET CLOSE
        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
        
        // SOCKET UX
        $("#chat-message-input").focus();
        $("#chat-message-input").on("keyup", function(e) {
            if (e.keyCode === 13) {  // enter, return
                $("#chat-message-submit").click();
            }
        });
        
        // SOCKET SEND MESSAGE
        $("#chat-message-submit").on("click", function(e){
            message_text = $("#chat-message-input").val();
            // If message is empty, don't send
            if (message_text == "") { return }
            chatSocket.send(JSON.stringify({
                'chat_id': active_chat_id,
                'message': message_text
            }));
            $("#chat-message-input").val("");
        });
    }

</script>
{% endblock %}

{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            <h5 class="title">Chat App</h5>
        </div>
    </div>


    <div class="content-wrapper">

        <!-- Row start -->
        <div class="row gutters">

            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

                <div class="card m-0">

                    <!-- Row start -->
                    <div class="row no-gutters" style="min-height: 615px;">
                        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-3 col-3">
                            <div class="users-container">
                                <!-- SEARCH BOX -->
                                <div class="container mb-3">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search...">
                                        <div class="input-group-append">
                                            <button class="btn btn-outline-warning" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>

                                <!-- USERS -->
                                <ul class="users">
                                    {% for chat in chats %}
                                    <li class="person" data-chat-id="{{ chat.id }}">
                                        <div class="user">
                                            <img src="https://www.bootdey.com/img/Content/avatar/avatar3.png">
                                            <span class="status online"></span>
                                        </div>
                                        <p class="name-time">
                                            {% for receiver in chat.members.all %}
                                                {% if receiver.id != current_user.id %}
                                                <span class="name">
                                                    {{ receiver.first_name }} {{ receiver.last_name }}
                                                </span>
                                                <span style="display: none;" class="id">{{ receiver.id }}</span>
                                                {% endif %}
                                            {% endfor %}
                                            <span class="time">{{ chat.update_time|date:"l - d M Y" }}</span>
                                        </p>
                                    </li>
                                    {% empty %}
                                    <div class="container">Henuz bir chat yok..</div>
                                    {% endfor %}
                                </ul>


                            </div>
                        </div>
                        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-9 col-9" style="background-color: aqua;">
                            <div class="container-fluid" id="no-chat-window">
                                <h4 style="text-align: center; padding-top: 100px;">First please select chat from left window.</h4>
                                
                            </div>
                            <div id="chat-window" style="display: none;">
                                <div class="selected-user">
                                <span>To: <span class="name" id="selected-user">Emily Russell</span></span>
                            </div>
                            <div class="chat-container" style="overflow-y: scroll; max-height: 500px; min-height: 500px;">
                                <ul class="chat-box chatContainerScroll">
                                </ul>
                            </div>
                            <div class="input-group container mt-2">
                                <input type="text" id="chat-message-input" class="form-control border-0 small" placeholder="Type message...">
                                <div class="input-group-append">
                                    <button id="chat-message-submit" class="btn btn-outline-warning" type="button">
                                        <i class="fas fa-paper-plane fa-sm"></i>
                                    </button>
                                </div>
                            </div>
                        
                            </div>
                            
                        </div>
                    </div>
                    <!-- Row end -->
                </div>

            </div>

        </div>
        <!-- Row end -->

    </div>
    <!-- Content wrapper end -->

</div>


{% endblock %}
<!-- <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html> -->

cargomarket/chatapp/templates/chatapp/room.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    <link rel="stylesheet" href="{% static 'chatapp/chat.css' %}"/>
</head>
<body>   
    {{ room_name|json_script:"room-name" }}

<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">

    <!-- Page header start -->
    <div class="page-title">
        <div class="row gutters">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                <h5 class="title">Chat App</h5>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            </div>
        </div>
    </div>
    <!-- Page header end -->

    <!-- Content wrapper start -->
    <div class="content-wrapper">

        <!-- Row start -->
        <div class="row gutters">

            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

                <div class="card m-0">

                    <!-- Row start -->
                    <div class="row no-gutters">
                        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-3 col-3">
                            <div class="users-container">
                                <div class="chat-search-box">
                                    <div class="input-group">
                                        <input class="form-control" placeholder="Search">
                                        <div class="input-group-btn">
                                            <button type="button" class="btn btn-info">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <ul class="users">
                                    <li class="person" data-chat="person1">
                                        <div class="user">
                                            <img src="https://www.bootdey.com/img/Content/avatar/avatar3.png" alt="Retail Admin">
                                            <span class="status busy"></span>
                                        </div>
                                        <p class="name-time">
                                            <span class="name">Steve Bangalter</span>
                                            <span class="time">15/02/2019</span>
                                        </p>
                                    </li>
                                    <li class="person" data-chat="person1">
                                        <div class="user">
                                            <img src="https://www.bootdey.com/img/Content/avatar/avatar1.png" alt="Retail Admin">
                                            <span class="status offline"></span>
                                        </div>
                                        <p class="name-time">
                                            <span class="name">Steve Bangalter</span>
                                            <span class="time">15/02/2019</span>
                                        </p>
                                    </li>
                                    <li class="person active-user" data-chat="person2">
                                        <div class="user">
                                            <img src="https://www.bootdey.com/img/Content/avatar/avatar2.png" alt="Retail Admin">
                                            <span class="status away"></span>
                                        </div>
                                        <p class="name-time">
                                            <span class="name">Peter Gregor</span>
                                            <span class="time">12/02/2019</span>
                                        </p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xl-8 col-lg-8 col-md-8 col-sm-9 col-9" style="background-color: lightgrey;">
                            <div class="selected-user">
                                <span>To: <span class="name">Emily Russell</span></span>
                            </div>
                            <div class="chat-container">
                                <ul class="chat-box chatContainerScroll">
                                </ul>
                                <div class="form-group mt-3 mb-0">
                                    <input type="text" class="form-control" id="chat-message-input" placeholder="Type your message here..."></input>
                                    <input id="chat-message-submit" class="btn-warning" type="button" value="Send">

                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Row end -->
                </div>

            </div>

        </div>
        <!-- Row end -->

    </div>
    <!-- Content wrapper end -->

</div>

<script>
    var me = Math.floor(Math.random() * 10 ) + 1;
    console.log("Me "+ me);
    function me_message(message) {
        var Dateobj = new Date();
        var f_message = '<li class="chat-right"><div class="chat-hour">' + Dateobj.getHours() + ':' + Dateobj.getMinutes();
        f_message += '<span class="fa fa-check-circle"></span></div><div class="chat-text">' + message + '</div>';
        f_message += '<div class="chat-avatar"><img src="https://www.bootdey.com/img/Content/avatar/avatar5.png" alt="Retail Admin"><div class="chat-name">Sam</div></div></li>';
        return f_message
    }
    function friend_message(message) {
        var Dateobj = new Date();
        var f_message = '<li class="chat-left">';
        f_message += '<div class="chat-avatar"><img src="https://www.bootdey.com/img/Content/avatar/avatar3.png" alt="Retail Admin"/><div class="chat-name">Russell</div></div>';            
        f_message += '<div class="chat-text">' + message + '</div>';
        f_message += '<div class="chat-hour">' + Dateobj.getHours() + ':' + Dateobj.getMinutes() + '<span class="fa fa-check-circle"></span></div>';
        f_message += '</li>';
        return f_message
    }

    const roomName = JSON.parse(document.getElementById('room-name').textContent);

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        // document.querySelector('#chat-log').value += (data.message + '\n');
        console.log(e);
        console.log("User Received" + data.user);
        console.log("Me "+ me);
        if (data.user == me){
            $(".chat-box").append(me_message(data.message));
        }
        else {
            $(".chat-box").append(friend_message(data.message));
        }
        

    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'user': me
        }));
        messageInputDom.value = '';
    };
</script>

</body>
</html>