cargomarket/cargomarket/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy, include
from django.contrib.auth.views import LoginView, LogoutView
from account.views import register, myprofile, home, change_password ,myprofile_edit, user_list,show_profile
from advertisement.views import ad_list, my_ad, update_ad, create_ad, detail_ad, delete_ad, all_ad ,recourse ,my_recourse, applicants_list ,state_set

urlpatterns = [
    path('', ad_list, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('accounts/register/', register, name='register'),
    path('accounts/myprofile/', myprofile, name='myprofile'),
    path('accounts/myprofile_edit/', myprofile_edit, name='myprofile_edit'),
    path('accounts/profile/id=<int:user_id>', show_profile, name='show_profile'),
    path('accounts/password/', change_password, name='password'),
    path('accounts/users/', user_list, name='users'),
    path('my_advertisement/', my_ad, name='my_ad'), 
    path('edit_advertiesement/<int:ad_id>', update_ad, name='edit_ad'),
    path('create_advertiesement/', create_ad, name='create_ad'),
    path('detail_advertiesement/<int:ad_id>', detail_ad, name='detail_ad'),
    path('delete_advertiesement/<int:ad_id>', delete_ad, name='delete_ad'),
    path('all_advertiesement/', all_ad, name='all_ad'), 
    path('recourse_advertiesement/<int:ad_id>', recourse, name='recourse'),
    path('my_recourse/', my_recourse, name='my_recourse'), 
    path('applicants/<int:ad_id>', applicants_list, name='app_list'),
    path('applicants/<int:app_id>/<int:state>', state_set, name='state_set'),
    path('chat/', include('chatapp.urls')),
]

cargomarket/chatapp/urls.py
from django.urls import path
from . import views

app_name = "chatapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('room/<str:room_name>/', views.room, name='room'),
    path('load/messages/', views.get_message, name='chat_message'),
    path('create/chat/', views.create_chat, name='create_chat'),
]

cargomarket/advertisement/models.py
from django.db import models
from django.contrib.auth.models import User
from account.models import License

# Create your models here.

class Advertisement(models.Model):
    ad_title = models.CharField('Ad Title', max_length=50)
    ad_explain = models.CharField('Ad Explain', max_length = 500)
    from_city = models.CharField('From City', max_length = 25)
    to_city = models.CharField('To City', max_length = 25)
    publish_date = models.DateField('Publish Date', auto_now_add=True)
    last_date = models.DateField('Last Date')
    total_weight = models.CharField('Product Weigth', max_length=25)
    total_volume = models.CharField('Product Volume', max_length=25)
    licenses = models.ManyToManyField(License, blank=True, verbose_name='Licenses')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ad_state=models.IntegerField('Ad State', default=1)
    ad_show=models.IntegerField('Ad Show', default=0)
    img = models.CharField('Img Select', max_length=400)


class Application(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) #user olarak düzelt
    add_id = models.IntegerField('Ad id') #ad_id olarak düzelt
    app_date = models.DateField('Application Date')
    app_state = models.IntegerField('app state', default = 0) #0 görülmemiş, 1 onaylanmış , 2 red
    

cargomarket/advertisement/forms.py
from advertisement.models import Advertisement, Application
from account.models import License

from django import forms
IMG_CHOICES= [
    ('#','Seçiniz'),
    ('https://images.unsplash.com/photo-1452948491233-ad8a1ed01085?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1053&q=80', 'Meyve ve Sebze'),
    ('https://images.unsplash.com/photo-1472141521881-95d0e87e2e39?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1052&q=80', 'Bakliyat'),
    ('https://images.unsplash.com/photo-1516199423456-1f1e91b06f25?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1032&q=80', 'Pertol'),
    ('https://images.unsplash.com/photo-1543389776-543c767cd200?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1050&q=80', 'Ev Eşyaları'),
    ('https://images.unsplash.com/photo-1549127024-5f213d45604a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1053&q=80', 'Cam vs Kırılıcak'),
    ('https://images.unsplash.com/photo-1471174466996-0aa69dbda661?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=924&q=80', 'Elektornik'),
    ('https://images.unsplash.com/photo-1547447379-7e2485fa95f8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', 'Demir ve Çelik'),
    ('https://images.unsplash.com/photo-1582282577230-2f59c636e60b?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1052&q=80', 'Odun Kereste'),
    ('https://images.unsplash.com/photo-1566125882500-87e10f726cdc?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=967&q=80', 'Zarf, Döküman'),
    ('https://images.unsplash.com/photo-1597074753149-53c386367bdf?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', 'Diğer'),
]
class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        #fields = '__all__'
        fields = ['ad_title','ad_explain', 'from_city', 'to_city', 'last_date', 'total_weight','total_volume','licenses', 'img']
        exclude = ['user']

    img = forms.CharField(widget=forms.Select(choices=IMG_CHOICES))
    licenses = forms.ModelMultipleChoiceField(queryset=License.objects.all(), widget=forms.CheckboxSelectMultiple)
    last_date = forms.CharField()

    # def save(self, *args, **kwargs):
    #     self.kwargs = 


class AdvertisementEditForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ['ad_title','ad_explain', 'from_city', 'to_city', 'last_date', 'total_weight','total_volume','licenses']
        exclude = ['user']

    licenses = forms.ModelMultipleChoiceField(queryset=License.objects.all(), widget=forms.CheckboxSelectMultiple)
    last_date = forms.CharField()


class ApplicationForm(forms.ModelForm):
    class Meta:
        model: Application
        fields = ['app_state']
        exclude = ['user']

cargomarket/advertisement/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from advertisement.models import Advertisement, Application
#from account.models import License
from advertisement.forms import AdvertisementForm, AdvertisementEditForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.timezone import localdate

# Create your views here.

@login_required
def ad_list(request):
    user = request.user
    search_post = request.GET.get('search')
    if search_post :
        advertisement = Advertisement.objects.filter(ad_title__contains=search_post, ad_state=1)
    else :
        advertisement = Advertisement.objects.filter(ad_state=1).order_by("-last_date").all()

    return render(request, template_name="adList.html", context={'user' : user, 'advertisement':advertisement})

@login_required
def create_ad(request):
    user = request.user
    #all_l = License.objects.all()
    if user.first_name :
        form = AdvertisementForm()    
        if request.method == 'POST':
            form = AdvertisementForm(request.POST)
            if form.is_valid():
                new_ad = form.save(commit=False)
                new_ad.user = user
                new_ad.save()
                messages.success(request, ('Kayıt Başarılı'))
                return redirect('my_ad')
            else :
                messages.error(request, ('Lütfen alanları eksiksiz doldurun.'))
        
        return render(request, template_name="createAd.html", context={'user':user, 'form':form}) #, 'all_l': all_l})

    else : 
        messages.error(request,('Önce Profil bilgilerinizi doldurunuz!'))
        return redirect('myprofile')
    

@login_required
def update_ad(request, ad_id):
    user = request.user
    adp = Advertisement.objects.get(id=ad_id)

    if request.method == 'POST':
        form = AdvertisementEditForm(request.POST, instance=adp)

        if form.is_valid():
            form.save()
            messages.success(request,('İlan Güncelleme Tamamlandı!'))
            return redirect('detail_ad', ad_id=ad_id)
    else:
        form = AdvertisementEditForm(instance=adp)


    return render(request, template_name='updateAd.html', context={'user':user, 'form':form, 'dltId':ad_id, 'last_date': str(adp.last_date) , 'adp':adp})

@login_required
def my_ad(request):
    user = request.user
    search_post = request.GET.get('search')
    if search_post :
        my_ad = Advertisement.objects.filter(ad_title__contains=search_post)
    else : 
        my_ad = Advertisement.objects.filter(user_id=request.user.id)

    return render(request, template_name="myAd.html", context={'user' : user, 'my_ad':my_ad})


@login_required
def detail_ad(request, ad_id):
    user = User.objects.get(id=request.user.id)
    form = Advertisement.objects.get(id=ad_id)
    own = Advertisement.objects.get(id=ad_id).user_id
        
    showApp = 0
    
    if Application.objects.filter(add_id=ad_id , user_id=request.user.id):
        showApp = 1    

    if request.user.id != own:
        show = Advertisement.objects.get(id=ad_id).ad_show
        show = show + 1  
        Advertisement.objects.filter(id=ad_id).update(ad_show = show)

    return render(request, template_name="detailAd.html", context={'user' : user, 'form':form, 'showApp':showApp})

@login_required
def delete_ad(request, ad_id):
    user = User.objects.get(id=request.user.id)
   
    Advertisement.objects.filter(id=ad_id).update(ad_state='0')

    messages.success(request,('İlan Silindi!'))
    return redirect('my_ad')
    
@login_required
def all_ad(request):
    search_post = request.GET.get('search')
    if search_post :
        ads = Advertisement.objects.filter(ad_title__contains=search_post)
    else : 
        ads = Advertisement.objects.all()

    return render(request, template_name="allAd.html", context={'ads':ads})

@login_required
def recourse(request, ad_id):
    user= User.objects.get(id=request.user.id)

    if user.first_name :
        app = Application()
        app.add_id = ad_id
        app.user_id = user.id
        app.app_state = 0
        app.app_date = localdate()
        app.save()       

        messages.success(request,('Başvurunuz iletildi!'))
        return redirect('detail_ad', ad_id=ad_id)
    else :        
        messages.error(request,('Önce Profil bilgilerinizi doldurunuz!'))
        return redirect('myprofile')

        

@login_required
def my_recourse(request):
    user = request.user
    search_post = request.GET.get('search')
    if search_post :
        adlist = Advertisement.objects.filter(ad_title__contains=search_post,ad_state=1)
    else : 
        adlist = Advertisement.objects.filter(ad_state=1).all() #ilan bilgilerini yazdırmak için tüm ilanlar çekilir, bu kod değişmeli

    applist = Application.objects.filter(user_id=user.id) #kullanıcın tüm başvuruları çekilir
    
    return render(request, template_name="myRecourse.html", context={"applist":applist, 'adlist':adlist})

@login_required
def applicants_list(request, ad_id):
    appList = Application.objects.filter(add_id=ad_id)#ilan numarasına ait başvurular çekilir
    ad = Advertisement.objects.get(id=ad_id)
    users = User.objects.all()

    return render (request, template_name="applicantsList.html", context={"appList":appList, "ad":ad, "users":users})

@login_required
def state_set(request, app_id ,state):
    Application.objects.filter(id=app_id).update(app_state=state)
    ad_id = Application.objects.get(id=app_id)
    print(ad_id)
    messages.success(request,('Durum değiştirildi'))
    return redirect('app_list', ad_id=ad_id.add_id)

cargomarket/advertisement/templates/adList.html
{% extends 'base/base.html' %}
{% block title %}Anasayfa{% endblock %}
{% block pagetitle %}Welcome{% endblock %}

{% block content %}

<div class="container-fluid">

    
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">İlanlar</h1>
        {% if request.user.companyprofile%}
            <a type="button" href="{% url 'create_ad' %}" class="btn btn-warning btn-circle btn-lg text-white"><i class="fa fa-plus"></i></a>
        {% endif%}
    </div>
    
    <div class="row" >
    {% for ad in advertisement%}
        <div class="col-xl-3 col-lg-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">{{ad.ad_title}}</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">{{ad.ad_title}}</div>
                            <a class="dropdown-item" href="{% url 'detail_ad' ad.id %}">İncele</a>
                            <a class="dropdown-item" href="{% url 'show_profile' ad.user_id %}">Profil Görüntüle</a>
                        </div>
                    </div>
                </div>
                
                <div class="card-body">
                    <div class="card" style="margin-bottom:0px">
                        <div class="img" >
                            <img src="{{ad.img}}" class="card-img-top" alt="..." style="height:200px">
                        </div>
                        <div class="card-body">
                          <p class="card-text">{{ad.ad_explain}}</p>
                          <a href="{% url 'detail_ad' ad.id %}" class="btn btn-secondary">Detay Görüntüle</a>
                        </div>
                        <div class="card-footer text-right">
                          <i class="fas fa-eye"></i> {{ad.ad_show}} 
                        </div>
                    </div>
                </div>
            </div>
        </div>
         {% endfor %}
    </div>
   
</div>
{% endblock %}

cargomarket/advertisement/templates/allAd.html
{% extends 'base/base.html' %}
{% block title %}İlanlarım{% endblock %}

{% block content %}
<div class="container-fluid offset-md-1 col-md-10 mb-3">
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tüm ilanlar</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <a class="btn btn-warning" href="{% url 'all_ad' %}"><i class="fas fa-arrow-left"></i></a>
                    <form action="{% url 'all_ad' %}"
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" style="float:right">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="İlan başlığını giriniz.."
                                aria-label="Search" aria-describedby="basic-addon2" name="search">
                            <div class="input-group-append">
                                <button class="btn btn-warning" type="submit" >
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                    <br/>
                    <br/>
                    {% if ads %}
                        <div class="row">
                            <div class="col-sm-12">
                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 69px;">Başlık</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 99px;">Yayınlanma Tarihi</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 53px;">Yayınlanma Durumu</th>
                                    <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 53px;">Görüntülenme Sayısı</th>
                                </tr>
                            </thead>
                            <tbody> 
                                {% for ad in ads %}                      
                                        <tr role="row" class="odd">
                                            <td class="sorting_1"><a href="{% url 'detail_ad' ad.id %}">{{ad.ad_title}}</a></td>
                                            <td>{{  ad.publish_date }} </td>
                                            {% if ad.ad_state == 1 %}
                                                <td> Aktif</td>
                                            {% else %}
                                                <td> Silindi </td>
                                            {% endif %}
                                            <td>{{  ad.ad_show }} </td>
                                        </tr>
                                {% endfor %}
                            </tbody>
                            </table>
                        </div>
                    {% else %}
                        <div class="offset-md-4 col-md-6">
                            <p>No polls are available.</p>
                            <i class="fad fa-forklift"></i>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

cargomarket/advertisement/templates/detailAd.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container-fluid">
        <div class="main-body">
            <div class="row gutters-sm">
                <div class="offset-md-2 col-md-8 mb-3" id="ilan">
                    {%csrf_token%}
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">İlan Detay</h6>
                                </div>
                                <div class="offset-md-2 col-sm-6 text-right">
                                {% if form.user_id != request.user.id %}
                                    <a href={% url 'show_profile' form.user_id %}>
                                        <h6 class="mb-0"><i class="fas fa-chalkboard-teacher"></i> Profil İncele</h6>
                                    </a>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 text-left">
                                        {{form.ad_title}}
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <i class="fas fa-eye"></i> {{form.ad_show}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row" style="margin-right: auto;margin-left: auto; width:250px; heigth:175px;">
                                    <img src="{{form.img}}" class="card-img-top" alt="...">
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Açıklama</h6>
                                    </div>
                                    <div class="col-sm-6 text-secondary">
                                        {{form.ad_explain}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Yayınlanma Tarih</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{form.publish_date }}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Son Tarih</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ form.last_date}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Nereden</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ form.from_city}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Nereye</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ form.to_city}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Toplam Ağırlık</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ form.total_weight}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">Toplam Hacim</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {{ form.total_volume}}
                                    </div>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h6 class="mb-0">İligli Sertifikalar</h6>
                                    </div>
                                    <div class="col-sm-9 text-secondary">
                                        {% for license in form.licenses.all %}
                                            {{license.license_name}}<br>
                                        {% endfor %}
                                    </div>
                                </div>
                                <hr>

                                <div class="row">
                                    <div class="col-sm-3">
                                    {% if form.user_id == request.user.id %}
                                        {% if form.ad_state == 1 %}
                                            <a class="btn btn-outline-warning" href="{% url 'edit_ad' form.id %}">Düzenle</a>
                                            <a class="btn btn-warning" href="{% url 'app_list' form.id %}">Başvurular</a>
                                        {% else %}
                                            <p>İlan Silindi <i class="fas fa-times"></i></p>
                                        {% endif %}
                                    {% elif request.user.driverprofile %}
                                        {% if showApp == 0 %}
                                            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#basvuruModal">Başvur</button></div>
                                        {% else %}
                                            Başvuru Yaptınız.<i class="fas fa-check"></i></div>
                                        {% endif %}
                                        <div class="col-sm-9" style="text-align:right">
                                            <button class="btn btn-outline-warning" id="new-chat-btn" type="button">
                                                <i class="fas fa-envelope fa-sm"></i> Mesaj At
                                            </button>
                                    {% endif %}
                                    </div>
                                </div>
                                <div class="modal fade" id="basvuruModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLongTitle">{{form.ad_title}}</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                {{form.ad_title}} başlıklı ilan için başvurunuzu onaylıyor musunuz?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                                                <a class="btn btn-success" href="{% url 'recourse' form.id %}">Onaylıyorum</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>                       
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block jscript %}
<script>

$("#new-chat-btn").on("click", function(){
    var target_user = {{form.user.id}};
    $.ajax({
        url: '{% url "chatapp:create_chat" %}',
        method: "POST",
        data: {
            "target_user_id": target_user,
            "csrfmiddlewaretoken": '{{ csrf_token }}',
        },
        dataType: 'json',
        success: function(data){
            chat_id = data['chat_id'];
            window.location.href = '{% url "chatapp:index" %}?chat_id='+chat_id;
        },
        error: function(err){
            console.log(err);
        }
    })
});
</script>

{% endblock %}